### ISSUE TITLE
Homebridge keeps giving errors. :/

### ISSUE THREAD

**Issue by Pentrucine** [wylanswets/homebridge-icontrol-platform#9]
Hello! After configuring the platform for icontrol in homebridge config.json, the accessory didn't show up in homekit. I have tried using the example accessory config and it gave me a bunch of errors. What should I do? 

Error: The requested accessory 'iControl' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\src\pluginManager.ts:198:15)
    at C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:330:29)
    at Server.start (C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:156:12)
    at cli (C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\src\cli.ts:80:10)
    at Object.<anonymous> (C:\Users\murad\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)

I am using the default platform config, and this accessory config:

{
  "accessories": [
    {
      "accessory": "iControl",
      "name": "Xfinity Home",
      "system": "XFINITY_HOME",
      "email": "your@email.com",
      "password": "<your password>",
      "pin": "<your 4-digit alarm pin code>"
    }
  ]
}

**Comment by wylanswets** [comment]
Hey @naji144 sorry for the delayed reply... if you are still having issues with this it looks like possibly the dependencies are not installed correctly. You could try running the command to install the plugin again, or try uninstalling the plugin and then run the install command again.
